### ISSUE TITLE
Timers still Crash on Android 7.1

### ISSUE THREAD

**Issue by guest4711** [philliphsu/ClockPlus#10]
While timers are fine now, settings Alarms still crashes....

class Loader references unknown path /dats/App/.  ../clock2-1/lib/arm

**Comment by antsuke42** [comment]
Changing the "time picker style" from "grid selector" to "system default" seems to fix this, and i can choose the time with the circle selector.

**Comment by guest4711** [comment]
Thanks. This Trick dies it. Numeric keypad works fine, too. Grid select is the culprit...

**Comment by vn971** [comment]
Confirming, "grid selector" crashes on my phone, and I have Android7.1. (To be precise, I have the non-stock CopperheadOS).

**Comment by philliphsu** [comment]
This should be fixed in v1.1.3 which is now up on F-Droid. Please try it out and confirm.

**Comment by guest4711** [comment]
Works for me now. Thanx for the fix and your good work.

**Comment by vn971** [comment]
It works, thank you! (CopperheadOS, android version 7.1.1., Clock+ 1.1.3)

**Comment by vn971** [comment]
(The issue can probably be closed now.)

**Comment by philliphsu** [comment]
Right, thanks all.
