### ISSUE TITLE
setting alarm makes clock+ crash  android7.0

### ISSUE THREAD

**Issue by paulle** [philliphsu/ClockPlus#11]
Setting alarm makes clock+ crash. I'm using android 7.0 (sony xperia xz).

**Comment by guest4711** [comment]
See issue #10. Changing timepickerstyle to System default or numeric keypad will help...

**Comment by philliphsu** [comment]
This should be fixed in v1.1.3 which is now up on F-Droid. Please try it out and confirm.

**Comment by paulle** [comment]
Thank you for the fix, tried it and now all is working well.

Am 11. März 2017 08:05:07 MEZ schrieb Phillip Hsu <notifications@github.com>:
>This should be fixed in v1.1.3 which is now up on F-Droid. Please try
>it out and confirm.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/philliphsu/ClockPlus/issues/11#issuecomment-285848945

-- 
K-9 Mail

**Comment by guest4711** [comment]
Works for me now. Thanx for the fix and your good work.
