### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by skmlcd** [philliphsu/ClockPlus#5]
Thanks for creating great app. Would it be possible to add it to F-Droid?

**Comment by philliphsu** [comment]
I'm currently not familiar with how it works, but I can do that.

**Comment by Primokorn** [comment]
Any news to have it working on Nougat? Thanks.

**Comment by philliphsu** [comment]
Fix for Nougat won't be a priority for a while.

**Comment by EdenDorf** [comment]
What a pity. I really would like to get it from F-Droid.

**Comment by krt16s** [comment]
If those crashes are the mayor blocker, you can set `maxSdkVersion` just like `minSdkVersion`, F-Droid honors those settings.

**Comment by philliphsu** [comment]
It is nice to see that there is still interest. I didn't think the app would still have attention, especially because the Google Clock was updated recently with killer features. Unfortunately, I can't possible devote enough time and energy to compete with that. Regardless, @krt16s I may take your suggestion in the coming week.

**Comment by skmlcd** [comment]
Well in my opinion you shouldn't compare your app to Google Clock, you should compare it to other Clock apps on the market. As far as I know yours app is the only one that has all the basic functionality, complies with Material Design and it is open source. That open source part is especially important since it allows you to upload it to F-Droid so people can actually have a good clock app without having Google Play Services installed on their phones. I'm part of this demographic. While it is a niche group of people, it is still important, because if consumer has a choice if they don't mind to be locked in Google's ecosystem (Play Store) or if they want complete Free experience (F-Droid).

**Comment by EdenDorf** [comment]
I totally agree with Skmlcd. I'm also totally free of googeservices at this point. And i would like to use your app. At this point of my personal progress i haven't the knowledge to compile my apk myself. 

Btw some suggestion: let us set timer's with days:hours:minutes. In some game's are really longtime timers. So i must not calculate it.

**Comment by revuwa** [comment]
+1 with @skmlcd 
I would love to see your app on F-Droid, so I could replace my (senseless) system-privileged Clock app with your great looking app >without< that 'killer features' I don't need anyway.

So please please with sugar on top, don't lose your enthusiasm on that fine piece of software!

**Comment by philliphsu** [comment]
I finally fixed it for Nougat. Now I will see about how to get it up on F-Droid.

**Comment by EdenDorf** [comment]
Yeah, nice. Thanks alot ヅ👍

**Comment by krt16s** [comment]
For F-Droid, see https://gitlab.com/fdroid/fdroiddata/commit/771beec51e9fcd4bc52b5b64e54d500312cbadea and https://gitlab.com/fdroid/fdroiddata/commit/84054a04303d0c548d655e43be86b098f24d4641. Should build tomorrow.

**Comment by philliphsu** [comment]
Great, thanks! Good to see someone was proactive without needing my involvement.

**Comment by Primokorn** [comment]
This app has all what I mean. No need to add new features IMHO.
Thanks both. Now available on [F-droid](https://f-droid.org/repository/browse/?fdfilter=clock&fdid=com.philliphsu.clock2).

**Comment by Primokorn** [comment]
Unfortunately I can't add a new alarm:
`03-07 09:37:19.907  8470  8470 E AndroidRuntime: Process: com.philliphsu.clock2, PID: 8470
03-07 09:37:19.908 1935 2697 W ActivityManager: Force finishing activity com.philliphsu.clock2/.MainActivity
03-07 09:37:20.412 1935 2042 W ActivityManager: Activity pause timeout for ActivityRecord{8c829fd u0 com.philliphsu.clock2/.MainActivity t247 f}
03-07 09:37:20.579 1935 2697 W ActivityManager: Force finishing activity com.philliphsu.clock2/.MainActivity
03-07 09:37:20.627 1935 2697 I ActivityManager: Killing 8470:com.philliphsu.clock2/u0a171 (adj 199): crash
03-07 09:37:20.645 1935 7874 I WindowManager: WIN DEATH: Window{3fefa08 u0 com.philliphsu.clock2/com.philliphsu.clock2.MainActivity}`
Android 7.1.1_r21

**Comment by philliphsu** [comment]
See issue #10 for a possible workaround.

**Comment by vn971** [comment]
The app is indeed on F-Droid now. Thanks!
(I become aware of the app because I saw it in the repo.)

**Comment by philliphsu** [comment]
I pushed an update earlier to the Play Store that *should* fix the crashing once and for all. As for F-Droid, I am still not familiar with its process but I heard that updates should be automatic if I tag my commits. Hopefully any of you can confirm this.

**Comment by Primokorn** [comment]
Yes, the [check mode](https://f-droid.org/wiki/page/com.philliphsu.clock2) is set to **Tags** so the update should be available in the coming days.
@krt16s will correct me if I'm wrong.

**Comment by krt16s** [comment]
The update check was set to lookout for tags that change the versioncode, but the update itself was a manual process. I updated the app in 5db791429e8c5b2bda46c558bf53984dd90997cf and also enabled automatic updates. As long as you don't change the overall structure, keep the tagging scheme and actually bump the version information, things should work out.
