### ISSUE TITLE
after upgrading  to Android 10 no more alarms

### ISSUE THREAD

**Issue by tessus** [philliphsu/ClockPlus#62]
After upgrading to Android 10, no alarms go off.

Actually all alarm clock apps do not work anymore, except the one that comes with Android.

**Comment by fatihbabacan92** [comment]
I have forked this project. Look for OneClock on Play Store. I'm actually pushing an update soon which will make this work with Android 10.

**Comment by BayramInanc** [comment]
Dostum tüm projeyi open source olarak göstermeye devam edecek misin

28 Eyl 2019 Cmt 21:57 tarihinde fatihbabacan92 <notifications@github.com>
şunu yazdı:

**Comment by tessus** [comment]
Useless app on Android 10. Moving on.
